export const ROBOT_REPOSITORY = Symbol('ROBOT_REPOSITORY');
export const ROBOT_CURRENT_STATE_REPOSITORY = Symbol(
  'ROBOT_CURRENT_STATE_REPOSITORY',
);
export const ROBOT_TELEMETRY_REPOSITORY = Symbol('ROBOT_TELEMETRY_REPOSITORY');
export const ROBOT_HEALTH_REPOSITORY = Symbol('ROBOT_HEALTH_REPOSITORY');
export const ALERT_REPOSITORY = Symbol('ALERT_REPOSITORY');
export const FLEET_READ_REPOSITORY = Symbol('FLEET_READ_REPOSITORY');
export const UNIT_OF_WORK = Symbol('UNIT_OF_WORK');
export const APP_LOGGER = Symbol('APP_LOGGER');
export const DATABASE_READINESS = Symbol('DATABASE_READINESS');
